print()
print("BIENVENIDO A CUENTOS DE CACTUSVILLE\nIngresa la siguiente información:\n")
Nombre=str(input("Ingresa tu Nombre: "))
Edad=int(input("Ingresa tu edad: "))
Color=int(input("Ingresa tu color favorito entre estas opciones numericas de los colores:\n\t(1. Rojo, 2. Azul, 3. Amarillo, 4. Verde, 5. Naranja, 6. Morado)\n"))
if Color==1:
      colorvaquero="Red"
elif Color==2:
      colorvaquero="blue"
elif Color==3:
      colorvaquero="yellow"
elif Color==4:
      colorvaquero="green"
elif Color==5:
      colorvaquero="orange"
elif Color==6:
      colorvaquero="violet"
def Marcos(): #Margenes para todos paneles de con diseño poligonal con medidas de 1050 de ancho y 650 de alto
    turtle.hideturtle()
    turtle.speed(50)
    turtle.penup()
    turtle.setpos(-525,325) 
    turtle.pendown()
    turtle.width(3)
    for i in range(2):
        turtle.forward(1050)
        turtle.right(90)
        turtle.forward(650)
        turtle.right(90)
    turtle.penup()
    turtle.setpos(-525,325) 
    turtle.pendown()
    for i in range(2):
        turtle.forward(1050)
        turtle.right(90)
        turtle.forward(75)
        turtle.right(90)
    turtle.penup()
    turtle.setpos(-525,-150) 
    turtle.pendown()
    for i in range(2):
        turtle.forward(1050)
        turtle.right(90)
        turtle.forward(175)
        turtle.right(90)
        turtle.speed(10)
    turtle.penup()
    turtle.goto(0,275)
    turtle.pendown()
    turtle.write(f"Tesoros de Cactusville: La Aventura de {Nombre}", False, "center", ("comic sans", 20))
def Desierto():
    turtle.fillcolor("DarkOrange")
    turtle.begin_fill()
    turtle.hideturtle
    turtle.speed(50)
    turtle.penup()
    turtle.setpos(-525,250) 
    turtle.pendown()
    turtle.width(3)
    for i in range(2):
        turtle.forward(1050)
        turtle.right(90)
        turtle.forward(400)
        turtle.right(90)  
        turtle.hideturtle()
    turtle.end_fill()
    turtle.fillcolor("CadetBlue1")
    turtle.begin_fill()
    turtle.speed(50)
    turtle.penup()
    turtle.setpos(-525,250) 
    turtle.pendown()
    turtle.width(3)
    for i in range(2):
        turtle.forward(1050)
        turtle.right(90)
        turtle.forward(250)
        turtle.right(90)  
    turtle.end_fill()
    def Cactus():
        turtle.hideturtle()
        turtle.fillcolor("green")
        turtle.begin_fill()
        turtle.speed(50)
        turtle.penup()
        turtle.setpos(250,0) 
        turtle.pendown()
        turtle.width(3)
        turtle.forward(40)
        turtle.left(90)
        turtle.forward(60)
        turtle.right(90)
        turtle.forward(30)
        turtle.left(90)
        turtle.forward(30)
        turtle.left(90)
        turtle.forward(15)
        turtle.left(90)
        turtle.forward(15)
        turtle.right(90)
        turtle.forward(15)
        turtle.right(90)
        turtle.forward(50)
        turtle.left(90)
        turtle.forward(40)
        turtle.left(90)
        turtle.forward(80)
        turtle.right(90)
        turtle.forward(15)
        turtle.right(90)
        turtle.forward(15)
        turtle.left(90)
        turtle.forward(15)
        turtle.left(90)
        turtle.forward(30)
        turtle.left(90)
        turtle.forward(30)
        turtle.right(90)
        turtle.forward(30)
        turtle.end_fill()
    Cactus()
    def Piedra():
        turtle.home()
        turtle.fillcolor("tomato4")
        turtle.begin_fill()
        turtle.speed(50)
        turtle.penup()
        turtle.setpos(-525,250) 
        turtle.pendown()
        turtle.width(3)
        turtle.right(90)
        turtle.forward(250)
        turtle.left(90)
        turtle.forward(350)
        turtle.left(90)
        turtle.forward(200)
        turtle.left(90)
        turtle.forward(100)
        turtle.right(90)
        turtle.forward(50)
        turtle.left(90)
        turtle.forward(250)
        turtle.end_fill()
    Piedra()
def Panel_Dibujo1():
    turtle.reset()
    turtle.hideturtle()
    Marcos()
    Desierto()
    turtle.speed(10)
    turtle.penup()
    turtle.goto(0,-275)
    turtle.pendown()
    turtle.write(f"En el desierto de Cactusville vivía {Nombre}, un vaquero valiente y aventurero de {Edad} años.\nUn día, encontró un mapa antiguo que prometía llevarlo a un tesoro perdido.\nEmocionado, decidió seguir las pistas del mapa en busca de riquezas y gloria.", False, "center", ("Arial", 20))
    def Vaquero1():
        v=turtle.Turtle()
        v.hideturtle()
        v.fillcolor("blue")
        v.begin_fill()
        v.speed(50)
        v.penup()
        v.setpos(-30,-40) 
        v.pendown()
        v.width(3)
        v.left(90)
        v.forward(50)
        v.right(90)
        v.forward(60)
        v.right(90)
        v.forward(50)
        v.right(90)
        v.forward(15)  
        v.right(90)
        v.forward(30)
        v.left(90)
        v.forward(30)
        v.left(90)
        v.forward(30)
        v.right(90)
        v.forward(15)
        v.end_fill()
        v.fillcolor(colorvaquero)
        v.begin_fill()
        v.right(90)
        v.forward(50)
        for i in range(2):
            v.forward(70)
            v.right(90)
            v.forward(60)
            v.right(90)
        v.forward(70)
        for i in range(2):
            v.left(90)
            v.forward(20)
            v.left(90)
            v.forward(50)
        v.right(90)
        v.forward(60)
        for i in range(2):
            v.forward(20)
            v.right(90)
            v.forward(50)
            v.right(90)
        v.backward(60)
        v.end_fill()
        v.fillcolor("white")
        v.begin_fill()
        for i in range(2):
            v.forward(10)
            v.right(90)
            v.forward(70)
            v.right(90)
        v.forward(50)
        for i in range(2):
            v.forward(10)
            v.right(90)
            v.forward(70)
            v.right(90)
        v.end_fill()
        v.backward(80)
        v.left(90) 
        v.fillcolor("bisque1")
        v.begin_fill() 
        for i in range(4):
            v.forward(120)
            v.right(90)
        v.forward(100)
        v.end_fill()
        v.fillcolor(colorvaquero)
        v.begin_fill() 
        v.left(90)
        v.forward(30)
        v.right(90)
        v.forward(30)
        v.right(90)
        v.forward(50)
        v.left(90)
        v.forward(20)
        v.right(90)
        v.forward(80)
        v.right(90)
        v.forward(20)
        v.left(90)
        v.forward(50)
        v.right(90)
        v.forward(30)
        v.right(90)
        v.forward(30)
        v.forward(120)
        v.end_fill()
        v.left(90)
        v.forward(40)
        v.left(90)
        v.fillcolor("black")
        v.begin_fill()
        v.penup()
        v.forward(40)
        v.pendown()
        for i in range(4):
            v.right(90)
            v.forward(25)
            v.right(90)
            v.forward(10)
        v.end_fill()
        v.penup()
        v.forward(50)
        v.pendown()
        v.fillcolor("black")
        v.begin_fill()
        for i in range(4):
            v.right(90)
            v.forward(25)
            v.right(90)
            v.forward(10)
        v.end_fill()
        v.penup()
        v.forward(40)
        v.pendown()
    Vaquero1()
    def Mapa():  #mapa debe estar a 70 mas del vaquero y la altura por determinar
        m=turtle.Turtle()
        m.hideturtle()
        m.penup()
        m.setpos(50,30) 
        m.pendown()
        m.speed(50)
        m.fillcolor("chocolate")
        m.begin_fill()
        m.width(4)
        for i in range(2):
            m.forward(100)
            m.right(90)
            m.forward(70)
            m.right(90)
        m.end_fill()
    Mapa()
def Panel_Dibujo2():
    turtle.reset()
    turtle.hideturtle()
    Marcos()
    Desierto()
    turtle.speed(10)
    turtle.penup()
    turtle.goto(0,-275)
    turtle.pendown()
    turtle.write(f"En su búsqueda, {Nombre} se topó con que cazarrecompensas acechaban su busqueda,\npero logro sortearlos y seguir con su camino. Aunque enfrentó desafíos como\ntormentas de arena y laberintos de cactus, nunca perdió el ánimo.", False, "center", ("Arial", 20))
    def Cazarrecompensas():
        x=50
        y=-40
        v=turtle.Turtle()
        v.hideturtle()
        v.fillcolor("black")
        v.begin_fill()
        v.speed(50)
        v.penup()
        v.setpos(x,y) 
        v.pendown()
        v.width(3)
        v.left(90)
        v.forward(50)
        v.right(90)
        v.forward(60)
        v.right(90)
        v.forward(50)
        v.right(90)
        v.forward(15)  
        v.right(90)
        v.forward(30)
        v.left(90)
        v.forward(30)
        v.left(90)
        v.forward(30)
        v.right(90)
        v.forward(15)
        v.end_fill()
        v.fillcolor("red")
        v.begin_fill()
        v.right(90)
        v.forward(50)
        for i in range(2):
            v.forward(70)
            v.right(90)
            v.forward(60)
            v.right(90)
        v.forward(70)
        for i in range(2):
            v.left(90)
            v.forward(20)
            v.left(90)
            v.forward(50)
        v.right(90)
        v.forward(60)
        for i in range(2):
            v.forward(20)
            v.right(90)
            v.forward(50)
            v.right(90)
        v.backward(60)
        v.end_fill()
        v.fillcolor("black")
        v.begin_fill()
        for i in range(2):
            v.forward(10)
            v.right(90)
            v.forward(70)
            v.right(90)
        v.forward(50)
        for i in range(2):
            v.forward(10)
            v.right(90)
            v.forward(70)
            v.right(90)
        v.end_fill()
        v.backward(80)
        v.left(90) 
        v.fillcolor("bisque1")
        v.begin_fill() 
        for i in range(4):
            v.forward(120)
            v.right(90)
        v.forward(100)
        v.end_fill()
        v.fillcolor("black")
        v.begin_fill() 
        v.left(90)
        v.forward(30)
        v.right(90)
        v.forward(30)
        v.right(90)
        v.forward(50)
        v.left(90)
        v.forward(20)
        v.right(90)
        v.forward(80)
        v.right(90)
        v.forward(20)
        v.left(90)
        v.forward(50)
        v.right(90)
        v.forward(30)
        v.right(90)
        v.forward(30)
        v.forward(120)
        v.end_fill()
        v.left(90)
        v.forward(40)
        v.left(90)
        v.fillcolor("black")
        v.begin_fill()
        v.penup()
        v.forward(40)
        v.pendown()
        for i in range(4):
            v.fillcolor("black")
            v.begin_fill()
            v.right(90)
            v.forward(25)
            v.right(90)
            v.forward(10)
            v.end_fill()
        v.end_fill()
        v.penup()
        v.forward(50)
        v.pendown()
        v.fillcolor("black")
        v.begin_fill()
        for i in range(4):
            v.fillcolor("black")
            v.begin_fill()
            v.right(90)
            v.forward(25)
            v.right(90)
            v.forward(10)
            v.end_fill()
        v.end_fill()
        v.penup()
        v.forward(40)
        v.pendown()
    Cazarrecompensas()
    def Vaquero2():
        v=turtle.Turtle()
        v.hideturtle()
        v.fillcolor("blue")
        v.begin_fill()
        v.speed(50)
        v.penup()
        v.setpos(-200,-40) 
        v.pendown()
        v.width(3)
        v.left(90)
        v.forward(50)
        v.right(90)
        v.forward(60)
        v.right(90)
        v.forward(50)
        v.right(90)
        v.forward(15)  
        v.right(90)
        v.forward(30)
        v.left(90)
        v.forward(30)
        v.left(90)
        v.forward(30)
        v.right(90)
        v.forward(15)
        v.end_fill()
        v.fillcolor(colorvaquero)
        v.begin_fill()
        v.right(90)
        v.forward(50)
        for i in range(2):
            v.forward(70)
            v.right(90)
            v.forward(60)
            v.right(90)
        v.forward(70)
        for i in range(2):
            v.left(90)
            v.forward(20)
            v.left(90)
            v.forward(50)
        v.right(90)
        v.forward(60)
        for i in range(2):
            v.forward(20)
            v.right(90)
            v.forward(50)
            v.right(90)
        v.backward(60)
        v.end_fill()
        v.fillcolor("white")
        v.begin_fill()
        for i in range(2):
            v.forward(10)
            v.right(90)
            v.forward(70)
            v.right(90)
        v.forward(50)
        for i in range(2):
            v.forward(10)
            v.right(90)
            v.forward(70)
            v.right(90)
        v.end_fill()
        v.backward(80)
        v.left(90) 
        v.fillcolor("bisque1")
        v.begin_fill() 
        for i in range(4):
            v.forward(120)
            v.right(90)
        v.forward(100)
        v.end_fill()
        v.fillcolor(colorvaquero)
        v.begin_fill() 
        v.left(90)
        v.forward(30)
        v.right(90)
        v.forward(30)
        v.right(90)
        v.forward(50)
        v.left(90)
        v.forward(20)
        v.right(90)
        v.forward(80)
        v.right(90)
        v.forward(20)
        v.left(90)
        v.forward(50)
        v.right(90)
        v.forward(30)
        v.right(90)
        v.forward(30)
        v.forward(120)
        v.end_fill()
        v.left(90)
        v.forward(40)
        v.left(90)
        v.fillcolor("black")
        v.begin_fill()
        v.penup()
        v.forward(40)
        v.pendown()
        for i in range(4):
            v.right(90)
            v.forward(25)
            v.right(90)
            v.forward(10)
        v.end_fill()
        v.penup()
        v.forward(50)
        v.pendown()
        v.fillcolor("black")
        v.begin_fill()
        for i in range(4):
            v.right(90)
            v.forward(25)
            v.right(90)
            v.forward(10)
        v.end_fill()
        v.penup()
        v.forward(40)
        v.pendown()
    Vaquero2()
def Panel_Dibujo3():
    turtle.reset()
    turtle.hideturtle()
    Marcos()
    def Cueva():
        turtle.fillcolor("SlateGray")
        turtle.begin_fill()
        turtle.hideturtle()
        turtle.speed(50)
        turtle.penup()
        turtle.setpos(-525,250) 
        turtle.pendown()
        turtle.width(3)
        for i in range(2):
            turtle.forward(1050)
            turtle.right(90)
            turtle.forward(400)
            turtle.right(90)  
            turtle.hideturtle()
        turtle.end_fill()
        turtle.fillcolor("bisque4")
        turtle.begin_fill()
        turtle.speed(50)
        turtle.penup()
        turtle.setpos(-525,250) 
        turtle.pendown()
        turtle.width(3)
        for i in range(2):
            turtle.forward(1050)
            turtle.right(90)
            turtle.forward(250)
            turtle.right(90)  
        turtle.end_fill()
        e=turtle.Turtle()
        e.hideturtle()
        e.speed(50)
        e.penup()
        e.setpos(-525,250)
        e.pendown()
        e.fillcolor("SlateGray")
        e.begin_fill()
        for i in range(10):
            for n in range(3):
                e.forward(60)
                e.right(120)
            e.forward(60)
            for n in range(3):
                e.forward(40)
                e.right(120)
            e.forward(40)
        e.end_fill()
    Cueva()
    def Cofre():
        c=turtle.Turtle()
        c.hideturtle()
        c.penup()
        c.setpos(250,-20) 
        c.pendown()
        c.speed(50)
        c.fillcolor("chocolate4")
        c.begin_fill()
        c.forward(100)
        c.left(90)
        c.forward(60)
        c.left(90)
        c.forward(100)
        c.left(90)
        c.forward(60)
        c.end_fill()
        c.fillcolor("chocolate4")
        c.begin_fill()
        c.backward(60)
        c.left(135)
        c.forward(50)
        c.left(315)
        c.forward(100)
        c.left(225)
        c.forward(50)
        c.left(45)
        c.forward(60)
        c.end_fill()
        c.fillcolor("chocolate4")
        c.begin_fill()
        c.right(225)
        c.forward(50)
        c.left(45)
        c.forward(60)
        c.right(30)
        c.forward(50)
        c.left(120)
        c.forward(100)
        c.left(60)
        c.forward(50)
        c.end_fill()
    Cofre()
    def Roca():
        r=turtle.Turtle()
        r.hideturtle()
        r.fillcolor("gray")
        r.begin_fill()
        r.penup()
        r.setpos(-350,50)
        r.pendown()
        for i in range(4):
            r.right(90)
            r.forward(120)
        r.end_fill()
        r.fillcolor("gray")
        r.begin_fill()
        r.penup()
        r.setpos(-275,-40)
        r.pendown()
        for i in range(4):
            r.right(90)
            r.forward(100)
        r.end_fill()
    Roca()
    def Vaquero3():
        x=1
        y=-50
        v=turtle.Turtle()
        v.hideturtle()
        v.fillcolor("blue")
        v.begin_fill()
        v.speed(50)
        v.penup()
        v.setpos(x,y) 
        v.pendown()
        v.width(3)
        v.left(90)
        v.forward(50)
        v.right(90)
        v.forward(60)
        v.right(90)
        v.forward(50)
        v.right(90)
        v.forward(15)  
        v.right(90)
        v.forward(30)
        v.left(90)
        v.forward(30)
        v.left(90)
        v.forward(30)
        v.right(90)
        v.forward(15)
        v.end_fill()
        v.fillcolor(colorvaquero)
        v.begin_fill()
        v.right(90)
        v.forward(50)
        for i in range(2):
            v.forward(70)
            v.right(90)
            v.forward(60)
            v.right(90)
        v.forward(70)
        for i in range(2):
            v.left(90)
            v.forward(20)
            v.left(90)
            v.forward(50)
        v.right(90)
        v.forward(60)
        for i in range(2):
            v.forward(20)
            v.right(90)
            v.forward(50)
            v.right(90)
        v.backward(60)
        v.end_fill()
        v.fillcolor("white")
        v.begin_fill()
        for i in range(2):
            v.forward(10)
            v.right(90)
            v.forward(70)
            v.right(90)
        v.forward(50)
        for i in range(2):
            v.forward(10)
            v.right(90)
            v.forward(70)
            v.right(90)
        v.end_fill()
        v.backward(80)
        v.left(90) 
        v.fillcolor("bisque1")
        v.begin_fill() 
        for i in range(4):
            v.forward(120)
            v.right(90)
        v.forward(100)
        v.end_fill()
        v.fillcolor(colorvaquero)
        v.begin_fill() 
        v.left(90)
        v.forward(30)
        v.right(90)
        v.forward(30)
        v.right(90)
        v.forward(50)
        v.left(90)
        v.forward(20)
        v.right(90)
        v.forward(80)
        v.right(90)
        v.forward(20)
        v.left(90)
        v.forward(50)
        v.right(90)
        v.forward(30)
        v.right(90)
        v.forward(30)
        v.forward(120)
        v.end_fill()
        v.left(90)
        v.forward(40)
        v.left(90)
        v.fillcolor("black")
        v.begin_fill()
        v.penup()
        v.forward(40)
        v.pendown()
        for i in range(4):
            v.fillcolor("black")
            v.begin_fill()
            v.right(90)
            v.forward(25)
            v.right(90)
            v.forward(10)
            v.end_fill()
        v.end_fill()
        v.penup()
        v.forward(50)
        v.pendown()
        v.fillcolor("black")
        v.begin_fill()
        for i in range(4):
            v.fillcolor("black")
            v.begin_fill()
            v.right(90)
            v.forward(25)
            v.right(90)
            v.forward(10)
            v.end_fill()
        v.end_fill()
        v.penup()
        v.forward(40)
        v.pendown()
    Vaquero3()
    def Recuerdos():
        x=250
        y=40
        c=turtle.Turtle()
        c.hideturtle()
        c.penup()
        c.setpos(x,y)
        c.pendown()
        for i in range(4):
            c.fillcolor("lightblue")
            c.begin_fill()
            x=x+20
            c.penup()
            c.setpos(x,y)
            c.pendown()
            c.circle(20)
            c.end_fill()
    Recuerdos()
    turtle.penup()
    turtle.goto(0,-275)
    turtle.pendown()
    turtle.speed(10)
    turtle.write(f"Finalmente, llegó al lugar del tesoro y encontró un cofre lleno de recuerdos perdidos.\nCada esfera contaba una historia emocionante sobre el desierto y sus habitantes.\n{Nombre} se dio cuenta de que la verdadera riqueza estaba en esas historias compartidas.", False, "center", ("Arial", 20))
def Panel_Dibujo4():
    turtle.reset()
    turtle.hideturtle()
    Marcos()
    Desierto()
    def Vaquero4():
        x=-10
        y=-50
        v=turtle.Turtle()
        v.hideturtle()
        v.fillcolor("lightblue")
        v.begin_fill()
        v.speed(50)
        v.penup()
        v.setpos(x,y) 
        v.pendown()
        v.width(3)
        v.left(90)
        v.forward(50)
        v.right(90)
        v.forward(60)
        v.right(90)
        v.forward(50)
        v.right(90)
        v.forward(15)  
        v.right(90)
        v.forward(30)
        v.left(90)
        v.forward(30)
        v.left(90)
        v.forward(30)
        v.right(90)
        v.forward(15)
        v.end_fill()
        v.fillcolor("lightblue")
        v.begin_fill()
        v.right(90)
        v.forward(50)
        for i in range(2):
            v.forward(70)
            v.right(90)
            v.forward(60)
            v.right(90)
        v.forward(70)
        for i in range(2):
            v.left(90)
            v.forward(20)
            v.left(90)
            v.forward(50)
        v.right(90)
        v.forward(60)
        for i in range(2):
            v.forward(20)
            v.right(90)
            v.forward(50)
            v.right(90)
        v.backward(60)
        v.end_fill()
        v.fillcolor("white")
        v.begin_fill()
        for i in range(2):
            v.forward(10)
            v.right(90)
            v.forward(70)
            v.right(90)
        v.forward(50)
        for i in range(2):
            v.forward(10)
            v.right(90)
            v.forward(70)
            v.right(90)
        v.end_fill()
        v.backward(80)
        v.left(90) 
        v.fillcolor("bisque1")
        v.begin_fill() 
        for i in range(4):
            v.forward(120)
            v.right(90)
        v.forward(100)
        v.end_fill()
        v.fillcolor("lightblue")
        v.begin_fill() 
        v.left(90)
        v.forward(30)
        v.right(90)
        v.forward(30)
        v.right(90)
        v.forward(50)
        v.left(90)
        v.forward(20)
        v.right(90)
        v.forward(80)
        v.right(90)
        v.forward(20)
        v.left(90)
        v.forward(50)
        v.right(90)
        v.forward(30)
        v.right(90)
        v.forward(30)
        v.forward(120)
        v.end_fill()
        v.left(90)
        v.forward(40)
        v.left(90)
        v.fillcolor("black")
        v.begin_fill()
        v.penup()
        v.forward(40)
        v.pendown()
        for i in range(4):
            v.fillcolor("black")
            v.begin_fill()
            v.right(90)
            v.forward(25)
            v.right(90)
            v.forward(10)
            v.end_fill()
        v.end_fill()
        v.penup()
        v.forward(50)
        v.pendown()
        for i in range(4):
            v.fillcolor("black")
            v.begin_fill()
            v.right(90)
            v.forward(25)
            v.right(90)
            v.forward(10)
            v.end_fill()
        v.penup()
        v.forward(40)
        v.pendown()
    Vaquero4()   
    def Recuerdos4():
        y=0
        c=turtle.Turtle()
        c.hideturtle()
        c.penup()
        c.setpos(80,y)
        c.pendown()
        c.fillcolor("lightblue")
        c.begin_fill()
        c.circle(20)
        c.end_fill()
        c.fillcolor("lightblue")
        c.begin_fill()
        c.penup()
        c.setpos(-40,y)
        c.pendown()
        c.circle(20)
        c.end_fill()
    Recuerdos4()
    turtle.penup()
    turtle.goto(0,-275)
    turtle.pendown()
    turtle.speed(10)
    turtle.write(f"Desde entonces, {Nombre} se convirtió en el guardián de los recuerdos del desierto,\ncompartiendo sus aventuras con todos. El desierto se convirtió en un lugar donde\nla magia de la aventura y la amistad florecían bajo el sol del Oeste.", False, "center", ("Arial", 21))
def Panel_Dibujo_5():
    turtle.reset()
    Marcos()
    Desierto()
    def Sol():
        sol=turtle.Turtle()
        sol.penup()
        sol.setpos(150,0)
        sol.pendown()
        sol.pencolor("red")
        sol.pensize(5)
        sol.fillcolor("yellow")
        sol.begin_fill()
        sol.hideturtle()
        sol.left(90)
        sol.circle(150,180)
        sol.left(90)
        sol.forward(300)
        sol.end_fill()
    Sol()
    def Vaquero5():
        i=3
        x=-10
        y=-50
        v=turtle.Turtle()
        v.hideturtle()
        v.fillcolor("lightblue")
        v.begin_fill()
        v.speed(50)
        v.penup()
        v.setpos(x,y) 
        v.pendown()
        v.width(3)
        v.left(90)
        v.forward(50/i)
        v.right(90)
        v.forward(60/i)
        v.right(90)
        v.forward(50/i)
        v.right(90)
        v.forward(15/i)  
        v.right(90)
        v.forward(30/i)
        v.left(90)
        v.forward(30/i)
        v.left(90)
        v.forward(30/i)
        v.right(90)
        v.forward(15/i)
        v.end_fill()
        v.fillcolor("lightblue")
        v.begin_fill()
        v.right(90)
        v.forward(50/i)
        for i in range(2):
            i=3
            v.forward(70/i)
            v.right(90)
            v.forward(60/i)
            v.right(90)
        v.forward(70/i)
        for i in range(2):
            i=3
            v.left(90)
            v.forward(20/i)
            v.left(90)
            v.forward(50/i)
        v.right(90)
        v.forward(60/i)
        for i in range(2):
            i=3
            v.forward(20/i)
            v.right(90)
            v.forward(50/i)
            v.right(90)
        v.backward(60/i)
        v.end_fill()
        v.fillcolor("white")
        v.begin_fill()
        for i in range(2):
            i=3
            v.forward(10/i)
            v.right(90)
            v.forward(70/i)
            v.right(90)
        v.forward(50/i)
        for i in range(2):
            i=3
            v.forward(10/i)
            v.right(90)
            v.forward(70/i)
            v.right(90)
        v.end_fill()
        v.backward(80/i)
        v.left(90) 
        v.fillcolor("bisque1")
        v.begin_fill() 
        for i in range(4):
            i=3
            v.forward(120/i)
            v.right(90)
        v.forward(100/i)
        v.end_fill()
        v.fillcolor("lightblue")
        v.begin_fill() 
        v.left(90)
        v.forward(30/i)
        v.right(90)
        v.forward(30/i)
        v.right(90)
        v.forward(50/i)
        v.left(90)
        v.forward(20/i)
        v.right(90)
        v.forward(80/i)
        v.right(90)
        v.forward(20/i)
        v.left(90)
        v.forward(50/i)
        v.right(90)
        v.forward(30/i)
        v.right(90)
        v.forward(30/i)
        v.forward(120/i)
        v.end_fill()
        v.left(90)
        v.forward(40/i)
        v.left(90)
    Vaquero5()
    def Caballo():
        i=3
        x=60
        y=-50
        v=turtle.Turtle()
        v.hideturtle()
        v.fillcolor("brown")
        v.begin_fill()
        v.width(5)
        v.speed(50)
        v.penup()
        v.setpos(x,y)
        v.pendown()
        v.forward(30/i)
        v.left(90)
        v.forward(50/i) 
        v.right(90)
        v.forward(50/i)
        v.right(90)
        v.forward(50/i)
        v.left(90)
        v.forward(30/i)
        v.left(90)
        v.forward(100/i)
        v.left(90)
        v.forward(80/i)
        v.right(90)
        v.forward(60/i)  
        v.left(90)
        v.forward(50/i)
        v.left(90)
        v.forward(20/i)
        v.right(90)
        v.forward(20/i)
        v.left(90)
        v.forward(40/i)
        v.left(90)
        v.forward(40/i)
        v.right(90)
        v.forward(100/i)
        v.end_fill()
        v.left(90)
        v.forward(30/i) 
        v.left(90)
        v.penup()
        v.forward(120/i) 
        v.pendown()
        v.fillcolor("beige")
        v.begin_fill()
        v.right(90)
        v.forward(20/i)
        v.right(90)
        v.forward(20/i)
        v.left(90)
        v.forward(30/i)
        v.right(90)
        v.forward(40/i)     
        v.right(90)
        v.forward(50/i)
        v.right(90)
        v.forward(80/i)
        v.end_fill()
    Caballo()
    turtle.penup()
    turtle.goto(0,-275)
    turtle.pendown()
    turtle.speed(10)
    turtle.write(f"Y así, {Nombre} y su fiel caballo, Rayo, cabalgaron hacia el horizonte\nen busca de nuevas aventuras. Porque en el vasto desierto de\nCactusville, la aventura nunca termina.", False, "center", ("Arial", 25))
import turtle
while True:
    Menudedibujos=int(input(("Ingresa el número de menú que deseas:\n1. Ver el cuento 'Aventuras en Cactusville'\n2. Ver un panel de dibujo\n3. Salir\n")))
    dibujar_menu=True
    while dibujar_menu:
        if Menudedibujos==1:
            while True:
                siguiente=int(input("Ingresa el número de dibujo para pasar hoja: Ejemplo:1, 2, 3, 4 o 5 (ingresa 6 para salir): "))
                if siguiente==1:
                    turtle.setup(1100,700)
                    Panel_Dibujo1()
                    turtle.penup()
                    turtle.setpos(0, -325)
                    turtle.pendown()
                    turtle.hideturtle()
                    turtle.write(f"{Nombre} presiona 2 en la consola para seguir", False,"center",("Arial",20))                    
                if siguiente==2:
                    turtle.setup(1100,700)
                    turtle.reset()
                    Panel_Dibujo2()
                    turtle.penup()
                    turtle.setpos(0, -325)
                    turtle.pendown()
                    turtle.hideturtle()
                    turtle.write(f"{Nombre} presiona 3 en la consola para seguir", False,"center",("Arial",20))                        
                elif siguiente==3:
                    turtle.setup(1100,700)
                    turtle.reset()
                    Panel_Dibujo3()
                    turtle.penup()
                    turtle.setpos(0, -325)
                    turtle.pendown()
                    turtle.hideturtle()
                    turtle.write(f"{Nombre} presiona 4 en la consola para seguir", False,"center",("Arial",20))                         
                elif siguiente==4:
                    turtle.setup(1100,700)
                    turtle.reset()
                    Panel_Dibujo4()
                    turtle.penup()
                    turtle.setpos(0, -325)
                    turtle.pendown()
                    turtle.hideturtle()
                    turtle.write(f"{Nombre} presiona 5 en la consola para seguir", False,"center",("Arial",20))                          
                elif siguiente==5:
                    turtle.setup(1100,700)
                    turtle.reset()
                    Panel_Dibujo_5()
                    turtle.penup()
                    turtle.setpos(0, -325)
                    turtle.pendown()
                    turtle.hideturtle()
                    turtle.write(f"{Nombre} presiona 6 para regresar al menu", False,"center",("Arial",20))         
                    break                 
                elif siguiente==6:
                    dibujar_menu=False
                    break
        elif Menudedibujos==2:
            while True:
                Panel=int(input(("Ingresa el número de Panel que deseas ver (6 para regresar):")))
                if Panel==1:
                    turtle.setup(1100,700)
                    Panel_Dibujo1()
                    turtle.penup()
                    turtle.setpos(0, -320)
                    turtle.pendown()
                    turtle.hideturtle()
                    turtle.write(f"{Nombre} escribe 6 en la consola para salir", False,"center",("Arial",20))
                elif Panel==2:
                    turtle.setup(1100,700)
                    Panel_Dibujo2()
                    turtle.penup()
                    turtle.setpos(0, -320)
                    turtle.pendown()
                    turtle.hideturtle()
                    turtle.write(f"{Nombre} escribe 6 en la consola para salir", False,"center",("Arial",20))                    
                elif Panel==3:
                    turtle.setup(1100,700)    
                    Panel_Dibujo3()
                    turtle.penup()
                    turtle.setpos(0, -320)
                    turtle.pendown()
                    turtle.hideturtle()
                    turtle.write(f"{Nombre} escribe 6 en la consola para salir", False,"center",("Arial",20))                    
                elif Panel==4:               
                    turtle.setup(1100,700)    
                    Panel_Dibujo4()
                    turtle.penup()
                    turtle.setpos(0, -320)
                    turtle.pendown()
                    turtle.hideturtle()
                    turtle.write(f"{Nombre} escribe 6 en la consola para salir", False,"center",("Arial",20))                    
                elif Panel==5:  
                    turtle.setup(1100,700)
                    Panel_Dibujo_5()
                    turtle.penup()
                    turtle.setpos(0, -320)
                    turtle.pendown()
                    turtle.hideturtle()
                    turtle.write(f"{Nombre} escribe 6 en la consola para salir", False,"center",("Arial",20))                    
                elif Panel == 6:
                    break  
        elif Menudedibujos==3:
            print(f"Buen día, {Nombre} espero que hayas disfrutado el cuento!")
            break
        else:
            print("Elige un número correcto de tu menú")